### ISSUE TITLE
How to run composer inside container

### ISSUE THREAD

**Issue by mrtuvn** [redbox-digital/magento-docker#1]
When i run bin/rd run in my home dir, i don't have permission to run composer
Could you tell me how to do that. Everything setup ok but when run rd i not a root so i can't run composer create something.. to install magento
If i try use sudo on container result show not found /bin/sh not found sudo command
![demo-redbox](https://cloud.githubusercontent.com/assets/1908873/22860495/35e91a38-f132-11e6-9425-06dacf685e6e.png)

**Comment by mrtuvn** [comment]
i have found how to fix
Just chmod src folder

**Comment by maxbucknell** [comment]
Yes chmod the src folder, but you can run rd fix-permissions to do this correctly. There is a section in the README too.
